-- CREATE DATABASE AND TABLES
-- Ramiro completed this
CREATE DATABASE Daycare;
USE Daycare;
create TABLE EMPLOYEE(
	EMP_ID			VARCHAR(10),
	EMP_LNAME		VARCHAR(15),
    EMP_FNAME		VARCHAR(15),
    DAYCARE_ID		VARCHAR(10),
    EMP_PHONE		VARCHAR(10),
    EMP_CITY		VARCHAR(15),
    EMP_STREET		VARCHAR(20),
    EMP_ZIP			VARCHAR(5),
    PRIMARY KEY(EMP_ID),
    FOREIGN KEY(DAYCARE_ID) REFERENCES DAYCARE(DAYCARE_ID)
);
CREATE TABLE CHILDREN(
	CHILD_ID		VARCHAR(10),
    CHILD_LNAME		VARCHAR(15),
    CHILD_FNAME		VARCHAR(15),
    CUS_ID			VARCHAR(10),
    CHILD_DOB		DATETIME,
    CHILD_AGE		INT(2),
    PRIMARY KEY(CHILD_ID),
    FOREIGN KEY(CUS_ID) REFERENCES CUSTOMER(CUS_ID)
);
CREATE TABLE CUSTOMER(
	CUS_ID			VARCHAR(10),
    CUS_LNAME		VARCHAR(15),
    CUS_FNAME		VARCHAR(15),
    DAYCARE_ID		VARCHAR(10),
    CUS_PHONE		VARCHAR(10),
    CUS_STREET		VARCHAR(20),
    CUS_CITY		VARCHAR(15),
    CUS_ZIP			VARCHAR(5),
    PRIMARY KEY(CUS_ID),
    FOREIGN KEY(DAYCARE_ID) REFERENCES DAYCARE(DAYCARE_ID)
);
CREATE TABLE DAYCARE(
	DAYCARE_ID		VARCHAR(10),
    DAYCARE_NAME	VARCHAR(25),
    PRIMARY KEY(DAYCARE_ID)
);

