-- CREATE DATABASE AND TABLES
-- Ramiro completed this
CREATE DATABASE DAYCARE;
use Daycare;
create TABLE EMPLOYEE(
	EMP_LNAME		VARCHAR(15),
    EMP_FNAME		VARCHAR(15),
    EMP_ID			VARCHAR(10),
    EMP_PHONE		VARCHAR(10),
    EMP_CITY		VARCHAR(15),
    EMP_STREET		VARCHAR(20),
    EMP_ZIP			VARCHAR(5),
    PRIMARY KEY(EMP_ID)
);
CREATE TABLE CHILDREN(
	CHILD_ID		VARCHAR(10),
    CHILD_LNAME		VARCHAR(15),
    CHILD_FNAME		VARCHAR(15),
    CHILD_DOB		DATETIME,
    CHILD_AGE		INT(2),
    PRIMARY KEY(CHILD_ID)
);
CREATE TABLE CUSTOMER(
	CUS_ID			VARCHAR(10),
    CUS_LNAME		VARCHAR(15),
    CUS_FNAME		VARCHAR(15),
    CHILD_ID		VARCHAR(10),
    CUS_PHONE		VARCHAR(10),
    CUS_STREET		VARCHAR(20),
    CUS_CITY		VARCHAR(15),
    CUS_ZIP			VARCHAR(5),
    PRIMARY KEY(CUS_ID),
    FOREIGN KEY(CHILD_ID) REFERENCES CHILDREN(CHILD_ID)
);
CREATE TABLE DAYCARE(
	DAYCARE_ID		VARCHAR(10),
    DAYCARE_NAME	VARCHAR(25),
    EMP_ID			VARCHAR(10),
    CUS_ID			VARCHAR(10),
    PRIMARY KEY(DAYCARE_ID),
    FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(EMP_ID),
    FOREIGN KEY(CUS_ID) REFERENCES CUSTOMER(CUS_ID)
);

